### ISSUE TITLE
Pinging causes game to hang

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#11]
**Mod Version**
Example: 1.3.1+1.20.2 server and client.

**Describe the bug**
I'm not sure what the cause is, but when I ping blocks with `Z`, the game hangs for about a 500ms with each press. If I hold the ping button the game freezes until I let go, if I'm lucky. If held for too long (say 10 seconds), the game cannot recover and I'm disconnected from the server:

```
[15:28:05] [Server thread/INFO]: X lost connection: Timed out
[15:28:05] [Server thread/INFO]: x left the game
[15:28:05] [Server thread/WARN]: handleDisconnection() called twice
```

Started after upgrading from 1.2.0 to 1.3.1.

Thanks.

**Comment by JackFred2** [comment]
Do you mean client lag or server lag? 

If the client, then I'm almost certain that it isn't caused by Eye Spy; all the client side does it check for the keybind, send a ping if so, and show the user a 1-time message for the mod. If you want to double check, then you can run a [Spark](https://spark.lucko.me/) profile with the following command while pinging, and share the result:

`/sparkc profiler start --threads * --timeout 20`

If the server, then I've just fixed an issue in 1.3.2 where the raycasting would load chunks; you can try that and see if it's fixed the issue. If not, install spark on the server and run the server-side command, and share the results:

`/spark profiler start --threads * --timeout 20`

I doubt it's Eye Spy though, I did some profiling and I'm getting sub-millisecond for a ping/rangefinder tick.

**Comment by redactedscribe** [comment]
> Do you mean client lag or server lag?

I'm not sure if it's affecting both, but certainly the client. I will downgrade Eye Spy on the server later and see if it changes anything.

**Comment by redactedscribe** [comment]
- Updated client and server to 1.3.2, no improvement.
- Noticed `Z` is also bound to  JourneyMap's "Show all Waypoints" key bind. Unbound it.
- Downgraded client and server to 1.2.0, no issue. (Probably just didn't notice the 20-30ms delay yet on this run, see next.)
- Upgraded server (only) to 1.3.1, no issue. Rebind `Z` to "Show all Waypoints".
- Upgraded client (only) to 1.3.1, minor issue: Frame skip (~20-30ms maybe) when pressing.
- Upgraded server (only) to 1.3.2, minor issue: Frame skip (~20-30ms maybe) when pressing.
- Upgraded client (only) to 1.3.2, minor issue: Frame skip (~20-30ms maybe) when pressing.
- Unbind Z from Eye Spy, same minor issue.
- Bind Z only to Eye Spy, no issue.

Not sure why I'm not getting anywhere close to the 500ms freezes any more on `Z`, but it appears that this is a JourneyMap issue and unrelated to Eye Spy. The confusion was due to Eye Spy rebinding the default pinging key from `F` to `Z` which made it look like Eye Spy was now broken, but it was just that both plugins were performing actions on `Z`, and JourneyMap is the culprit (`journeymap-1.20.2-5.9.18-fabric.jar`).

This should be fine to close.

**Comment by JackFred2** [comment]
Strange issue; I appreciate the thorough debugging. Glad you solved it.
