### ISSUE TITLE
Ability to see distance of pinged object when object is anywhere on screen

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#15]
**Is your feature request related to a problem? Please describe.**

Currently we have to look at the approximate location of a pinged object to see its distance from us. This is not a bad feature alone, but I feel like being able to always see the distance if the pinged object is somewhere on screen would help. In particular, pings which are far away aren't always easy to spot, with distance always shown, this would become trivial. This could also help if pinging dropped items becomes a thing (#14) as items are small even when nearby.

**Describe the solution you'd like**

If a ping is somewhere on screen, show the distance. To prevent having numerous distance figures floating around for each of the 5 pings (default max), this option could/should only show the distance to the last pinged object, and the other 4 requiring the current behaviour of needing to be approximately looked at.

**Describe alternatives you've considered**

Get new glasses.

Thanks.

**Comment by JackFred2** [comment]
I've changed the cursor mode; it'll now be always visible but scale down to a minimum threshold which will be changeable in the config. Additionally, it'll keep max size for a second so you'll notice it easier. Of course, if you always want it full size you can change `minimumScale` to `1`.

![juWWFV2F3v](https://github.com/JackFred2/EyeSpy/assets/8350692/821a0cd8-3473-4c2d-9944-efa76ff21752)

(text is only grainy because the window is small for gif recording, it looks fine on an e.g. 1080p, and there's the `/eyespy config text textScale` option

**Comment by JackFred2** [comment]
1.3.4
