### ISSUE TITLE
incompatibility with Language Reload

### ISSUE THREAD

**Issue by peow** [JackFred2/EyeSpy#16]
**Mod Version**
Eye Spy 1.3.5+1.20.1

**Describe the bug**
The Language Reload mod allows you to do bilingual searches, for example I can search for "planks" in English in the creative menu, even though my game is in another language, however when using the Eye Spy mod, the bilingual search stops working

**To Reproduce**
https://modrinth.com/mod/language-reload/version/1.5.10+1.20.1
https://modrinth.com/mod/eye-spy/version/1.3.5+1.20.1
Minecraft Fabric 1.20.1

**Log File**
[latest.log](https://github.com/JackFred2/EyeSpy/files/14216655/latest.log)

**Screenshots (Optional)**
* **without** Eye Spy
![2024-02-08_23 35 25](https://github.com/JackFred2/EyeSpy/assets/105888751/f449d7d1-89a1-4fa8-8f06-473fc3bdaae5)

* **with** Eye Spy
![2024-02-08_23 33 33](https://github.com/JackFred2/EyeSpy/assets/105888751/d6b5a860-6426-4ab6-9f1b-99f0194061dd)

-----------------

if possible pls make an update to fabric 1.20.1

**Comment by JackFred2** [comment]
Looks to be a conflict between Language Reload [in this mixin](https://github.com/Jerozgen/LanguageReload/blob/master/src/main/java/jerozgen/languagereload/mixin/MinecraftClientMixin.java#L20) and (bundled with Eye Spy) Server Translations API's [SystemDelegatedLanguage](https://github.com/NucleoidMC/Server-Translations/blob/1.20/api/src/main/java/xyz/nucleoid/server/translations/mixin/LanguageMixin.java) - Language Reload only works with a `ClientLanguage`/`TranslationStorage`object but STAPI wraps it with it's own to use server translations if needed.

I'm not sure which side this needs to be fixed in, though I'll open an issue for language reload.

**Comment by peow** [comment]
ok, thanks

**Comment by JackFred2** [comment]
Fixed in Language Reload

**Comment by peow** [comment]
tysm for your help
