### ISSUE TITLE
Trigger ping key (`F`) only once when held

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#9]
**Mod Version**
Example: 1.0.2+1.20.2

**Describe the bug**
It's possible to hold the ping key (`F` by default) and spam pings. Seems more like a bug than a poorly implemented feature. It's possible this cannot be controlled as another ping mod has the same issue.

**Expected behavior**
Ping once, even if `F` is held.

**To Reproduce**
Hold `F` on a block.

Thanks!

**Comment by JackFred2** [comment]
Not an Eye-Spy related issue, it's just your keyboard repeating the inputs if the key is held down. You see the same issue in vanilla if you hold the inventory button (`E`) down.

For what it's worth, I've added a max ping limit in the new version so that players can only have e.g. 5 pings active at once. If it becomes too much of an issue I'll add a rate limiter as well.

**Comment by redactedscribe** [comment]
It wasn't the number of active pings that was an issue from my perspective, but more so the rate. It can be held indefinitely. As you said, if others complain, might be worth rate-limiting it.
